### ISSUE TITLE
没有密码页面

### ISSUE THREAD

**Issue by alanqing007** [Mikuu/Micoo#41]
打开 localhost:8123，直接跳转到登录页面：
![image](https://user-images.githubusercontent.com/29423391/135065923-80ed0cc2-05ef-45f5-939e-3c36c22dfc96.png)
怎么没有看到密码页面呢？

**Comment by Mikuu** [comment]
你安装完成后，如果先发送curl命令再打开页面，也会跳过密码页面的，所以想先确定一下，安装完成后是直接打开浏览器，还是每次都先curl了一次呢？

另外，目前缓存的处理可能还有些问题（没来得及改），建议新起服务后，先清空浏览器的cookie，再访问页面，或者使用隐身模式。
