### ISSUE TITLE
engine接口上传的时候报404，8123和3001端口都尝试过

### ISSUE THREAD

**Issue by jiangyingforSH** [Mikuu/Micoo#47]

**Comment by Mikuu** [comment]
大兄弟，好歹赏几个具体的描述吧，你启动服务的方式、你客户端的具体配置等等；

如果是docker-compose在本地启动的，一般是localhost:8123/engine，如果是本地代码启动的，一般是localhost:3002/engine

**Comment by jiangyingforSH** [comment]
大佬，不好意思，刚冒昧了，我用的是Java客服端发送的，启动方式安装文档的第二种，端口号，我后面使用了3002，这个是服务端的日志，
![image](https://user-images.githubusercontent.com/23260726/147049120-1c0cfc37-33e0-40db-adf6-96585cd562ac.png)
这个是客户端的请求配置
![image](https://user-images.githubusercontent.com/23260726/147049250-6fd8f57d-8764-43ec-a70c-6c66d0fda07e.png)

**Comment by Mikuu** [comment]
不好意思，我上面的回复写错了一个地方（已经更正了）：
当使用代码在本地启动时，engine的url不包含/engine，只有在docker-compose启动时才需要，具体来说就是：
容器启动时，上传图片的url是：http://localhost:8123/engine
代码启动时，上传图片的url是：http://ocalhost:3002/

**Comment by jiangyingforSH** [comment]
大佬，还有个小问题，我刚按照你的方式可以了，但是图片没有上传上去（我在exchange目录里面没有找到）
![image](https://user-images.githubusercontent.com/23260726/147053552-a90c11e1-582f-4556-98d9-374322fffb94.png)
还有一个就是用客户端请求，但是这个报错400，pid不存在，但是实际在micoo前端页面能够看到有请求到了，只是里面没有图片
![image](https://user-images.githubusercontent.com/23260726/147054242-9b687b35-05fe-40ff-bfc9-3b21d23ff3c0.png)
![image](https://user-images.githubusercontent.com/23260726/147054240-3b931596-7afa-46c2-aef3-9fb7b4c57fe4.png)

**Comment by jiangyingforSH** [comment]
![image](https://user-images.githubusercontent.com/23260726/147054397-24c1131f-211e-4411-9a90-67cfe2042927.png)

**Comment by Mikuu** [comment]
有几个问题：
1. 你是在自己的本地电脑上启动的服务还是在另外一台服务器（或者云服务）上启动的服务？我看你访问的方式是用的110.42.200.195的IP地址，我猜测是远端服务。

2. 我看你的exchange目录是创建在系统根目录下的，/exchange/file-server/xxxx，这种方式一般是使用容器启动的才会把exchange目录创建在系统根目录下，但你上面说你用的第二种方式启动的，那应该是用代码启动的，代码启动的话，应该是../exchange/file-server/xxxx这个相当路径才对。如果你确实是用代码方式启动的engine服务，请检查一下你engine目录下运作./run.sh的环境下，有没有MICOO_ENV这个环境变量，如果有MICOO_ENV=docker，那代码启动的时候，也会在根目录下创建exchange目录，

如果exchange目录不对，上传文件会失败的，但你报的错比较奇怪，看起来是用容器启动的配置进行了代码启动，你可以按照我上面说的检查一下

**Comment by Mikuu** [comment]
pid不存在那个，我就看不懂了，应该不会呀，我从来没需要到过这样的 T_T

**Comment by jiangyingforSH** [comment]
谢谢大佬，我直接按第三种方式容器化启动后，上面的问题都没有了；我是使用的云服务器
但是，有2个小小的问题。
1.就是会出行502，重启容器后正常，但是1-2次后就又会出现。
![image](https://user-images.githubusercontent.com/23260726/147070641-11ecd55b-a418-4d84-8a70-023bd05575f1.png)


2.我将构建编号7这个设置了基准图，但是构建编号8并没有触发图像对比
![image](https://user-images.githubusercontent.com/23260726/147070485-c8237dcd-d472-47fb-afab-4de2c2a55262.png)

![image](https://user-images.githubusercontent.com/23260726/147070442-60a9641d-2049-4761-b76a-8136486664ad.png)

**Comment by Mikuu** [comment]
比较不成功，invalid png buffer，你是不是用的非标准格式的png图片？

如果nginx出现5xx，看看是不是engine或者dashboard服务挂掉了，有些异常处理可能还不是很完善，遇到一些我没考虑到的边界或者极端情况，有可能容器内的服务会挂掉，然后nginx就会报5xx

**Comment by jiangyingforSH** [comment]
辛苦大佬的指点。另外有个小小的请求，就是帮忙隐藏下第二段回复的那个ip地址，感谢
