### ISSUE TITLE
设置忽略区域后，再次尝试，diff值还是一样

### ISSUE THREAD

**Issue by jiangyingforSH** [Mikuu/Micoo#48]
在构建编号56时，我的diff值是0.1812%，我点击pass，然后设置忽略区域，把状态栏忽略，再次构建，编号57，但是发现diff值还是0.1812%
![Home  demo  56](https://user-images.githubusercontent.com/23260726/147312245-bd4008ff-d91f-42cc-9ea7-6e43654f9852.png)
![Home  demo  57](https://user-images.githubusercontent.com/23260726/147312254-673a6923-cd1c-4d61-ae00-7144d35c1baa.png)

**Comment by Mikuu** [comment]
忽略区域只是忽略diff对自动判定的影响，0.1812%的差异只要客观存在，就不会是零，但使用忽略区域后，自动判定的结果应该是Pass，而不是Fail，当然，前提是diff的内容全部在忽略区域之内；

另外，两个小tips：

1. 有时候你用忽略框已经忽略了差异，但自动对比还是Fail，就需要仔细查看一下还有没有别的漏掉的差异，即便是很小的点，都会Fail的；
2. 如果是mobile的测试，对于顶端状态栏，建议在测试之前，使用android或者iOS的命令，将顶端的各种状态固定，比如时间都固定在11:50，信号、电量都是满格等，可以减少对比干扰。因为忽略框的使用虽然可以排除干扰，但会降低对比速度，忽略框越多对比越慢，而手机状态栏是每个页面都有的，损坏会非常大；
