### ISSUE TITLE
请问有没有在kubernetes上部署的案例呢，如何处理volumes

### ISSUE THREAD

**Issue by jindong-zhang-git** [Mikuu/Micoo#60]
如题，想试着在项目上引入Micoo做图像测试服务。目前项目上使用的是kubernetes，所以想问一下有没有使用k8s的案例。

上k8s目前我能想到的问题有：
1. micoo-nginx服务提供的是什么功能，是否能被k8s的ingress层所代替？
2. micoo的各个服务是无状态的吗？看docker-compose中似乎用到了volumes，volumes在k8s环境中如何处理？

感谢！

**Comment by jindong-zhang-git** [comment]
另外能不能集成远程的mongodb（比如aws上的）

**Comment by Mikuu** [comment]
Micoo在我所知道的很多项目上，都是使用K8S来部署的，所以部署是没有问题的：
1. micoo-nginx的作用就是提供一个反向代理，整个后端有三个部分：dashboard service、engine service以及一个简单的file service（就是nginx自身），为了对外提供统一的访问入口，使用nginx作为反向代理。单从反向代理的角度来说，Ingress是可以替代的；
2. 服务是没有状态的，只有资源才有状态；
3. 至于volume的问题，不同的云厂商提供的持续存储的方案是不一样的，建议结合你们自己的环境，找Devops的同学看看怎么弄最合适；
4. mongodb可以使用云原生的数据库替代，但需要微调一些配置细节；

**Comment by jindong-zhang-git** [comment]
> 至于volume的问题，不同的云厂商提供的持续存储的方案是不一样的，建议结合你们自己的环境，找Devops的同学看看怎么弄最合适；

所以这里用到的volume需要是persistent volume是吧，pod销毁之后也需要保留数据的那种？那我再研究一下，还没有配置过这类型的volume

**Comment by Mikuu** [comment]
是的，volume最好使用PV，不然pod销毁后截图就都没有了

**Comment by jindong-zhang-git** [comment]
Hello, 能请问`exchange-volume`需要多大的空间吗，从名字上看只是用来交换的话似乎不需要很大的volume？

**Comment by Mikuu** [comment]
这个是用来存储截图的，理论上如果你不手动清除的话，是会无限增加的。名字叫exchange是因为它被不通的服务共用。
