### ISSUE TITLE
关于Project配置项说明

### ISSUE THREAD

**Issue by Arah231** [Mikuu/Micoo#61]
![image](https://user-images.githubusercontent.com/1888005/173515740-98e43bbd-40ac-4070-a240-9a2084d4fcf7.png)
项目配置项中，有几项在文档中没有找到效果和配置的介绍，能否请简单做下说明，是否是跟图片一些差异忽略相关的
Detect Antialiasing
Color Threshold
Ignoring Cluster
Ignoring Cluster Size

**Comment by Mikuu** [comment]
不好意思，一直没有时间补这部分的文档：
[Detect Antialiasing](https://github.com/Prior99/native-image-diff#:~:text=to%20true%20(default).-,Antialiasing%20Detection,-By%20default%20this);
[Color Threshold](https://github.com/Prior99/native-image-diff#:~:text=false%20as%20detectAntialiasing.-,Color%20threshold,-It%27s%20possible%20to);
Ignoring Cluster 和 Ignoring Cluster Size 主要是配置区域忽略功能的逻辑算法的，是否使用忽略族，这个和区域忽略的效率有一定关系，但影响较小，几乎可以忽略不计；

**Comment by Arah231** [comment]
感谢回复~
