### ISSUE TITLE
question - recursively find screenshots inside screenshot subfolders

### ISSUE THREAD

**Issue by maugap-idocket** [Mikuu/Micoo#62]
This is a question: Is there a plan to include the functionality to recursively find all the files on the screenshot folder?

I have a framework that captures the images and separates them into different scenario folders.

Then I have to copy all of those screenshots into a general folder so Micoo can pick them up.

**Comment by Mikuu** [comment]
hi @maugap-idocket,

I did had considered this functionality in micooc (the client) previously, but finally didn't implement it, below are some considerations:

- usually when we use subfolders to contain screenshots, there would probably be some meanings to the subfolder names, just like your case, I guess you may name your subfolder with your scenario name or index, then the test case name could probably = subfolder name + screenshot filename, however, this may or may not be every user wanted, besides, if consider the subfolder depth, this issue could be more complicated,
- if ignore the subfolder name and keep use screenshot filename from all subfolders as their test case name, there could be the problem of duplicated screenshot filename,

so, if micooc implements this functionality in some way, there would probably be some uncertain issues and make the logic complicated, then I decided to leave this to the users to collect their screenshots together into a folder, just like what you have done, which I think is an easy work and can satisfy every user's need.

Hope this can answer your question.
