### ISSUE TITLE
启动docker compose时，镜像micoo-dashboard和micoo-engine不能启动成功

### ISSUE THREAD

**Issue by brak3** [Mikuu/Micoo#70]
![image](https://user-images.githubusercontent.com/56919405/229854837-ef63edf3-89a0-4759-85d7-07ded0a5c216.png)

![image](https://user-images.githubusercontent.com/56919405/229854925-6461cbbf-b2d2-41c9-9175-792ca702004f.png)

**Comment by Mikuu** [comment]
请问你的运行环境是怎么样的？比如操作系统版本、docker的版本这些。我这边目前没有复现这个问题。
